version: '3'

services:
  nginx_reverse_proxy:
    build:
         context: ./nginx
         dockerfile: Dockerfile
    container_name: nginx_reverse_proxy
    ports:
      - "9090:80"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
       - /var/log/nginx
      
      
        

     